#add implentation
def add(x,y):
    return x+y
#sub implentation    
def sub(x,y):
    return x-y
#mul implentation
def mul(x,y):
    return x*y
#div implentation
def div(x,y):
    return x/y
#square implementation
def square(x):
    return x*x